# environment and task
env:
  name: HalfCheetah-v4
  task: ""
  library: gymnasium
  max_episode_steps: 1000
  seed: 42

# collector
collector:
  total_frames: 1_000_000
  init_random_frames: 25_000
  frames_per_batch: 1000
  init_env_steps: 1000
  reset_at_each_iter: False
  device:
  env_per_collector: 1


# replay buffer
replay_buffer:
  size: 1000000
  prb: 0 # use prioritized experience replay
  scratch_dir: null

# optimization
optim:
  utd_ratio: 1.0
  gamma: 0.99
  loss_function: l2
  lr: 3.0e-4
  weight_decay: 1e-4
  batch_size: 256
  target_update_polyak: 0.995
  device: null

# network
network:
  hidden_sizes: [256, 256]
  activation: relu
  noise_type: "ou" # ou or gaussian

compile:
  compile: False
  compile_mode:
  cudagraphs: False

# logging
logger:
  backend: wandb
  project_name: torchrl_example_ddpg
  group_name: null
  exp_name: ${env.name}_DDPG
  mode: online
  eval_iter: 25000
  video: False
  num_eval_envs: 1
