# Logger
logger: wandb
exp_name: discrete_sac
record_interval: 1
mode: online

# Environment
env_name: CartPole-v1
frame_skip: 1
from_pixels: false
reward_scaling: 1.0
init_env_steps: 1000
seed: 42

# Collector
env_per_collector: 1
max_frames_per_traj: 500
total_frames: 1000000
init_random_frames: 5000
frames_per_batch: 500 # 500 * env_per_collector

# Replay Buffer
prb: 0
buffer_size: 1000000

# Optimization
utd_ratio: 1.0
gamma: 0.99
batch_size: 256
lr: 3.0e-4
weight_decay: 0.0
target_update_polyak: 0.995
target_entropy_weight: 0.2
# default is 0.98 but needs to be decreased for env
# with small action space

device: cpu
