# @package _global_
defaults:
  - mode: ${mode:async}
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

env:
  dataset: math
  num_envs: 32
  repeats: 16
  reasoning: false
  max_steps: 2

model:
  name: Qwen/Qwen2.5-7B
  compile: false

train:
  exp_name: "grpo-math"
  mixed_precision: true
  total_dialog_turns: 200_000
  packing: false
  dialog_turns_per_batch: 32
  gradient_accumulation_steps: 16
  checkpoint_frequency: 100
  optim_batch_size: 64
  buffer_size: 4096
  weight_update_frequency: 1
  kl_coef_in_loss: true
  use_kl_to_ref: false
  kl_to_ref_coeff: 0.0
  kl_to_inference_coeff: 1e-2
  entropy_coeff: 1e-4
  logging_frequency: 10
  empty_replay_buffer: false

train_model:
  gradient_checkpointing: true
  num_devices: 2
  lora:
    enabled: false
    r: 0
    alpha: 0
    dropout: 0.0
  quantization:
    enabled: false
  attn_implementation: flash_attention_2
  torch_dtype: bfloat16

inference_model:
  num_devices: 6
  quantization:
    enabled: false
  attn_implementation: flash_attention_2
  torch_dtype: bfloat16
  gpu_memory_utilization: 0.9
  temperature: 1.0
  top_p: 0.95
  max_tokens: 2048
  include_stop_str_in_output: true
  enforce_eager: false

ref_model:
  gradient_checkpointing: false
  num_devices: 1
  lora:
    enabled: false
    r: 0
    alpha: 0
    dropout: 0.0
  quantization:
    enabled: false
  attn_implementation: flash_attention_2
  torch_dtype: bfloat16

optimizer:
  name: AdamW
  lr: 5e-6
  clip_grad_norm: 1.0
  weight_decay: 0.01

ray:
  init_config:
    num_cpus: 96
    num_gpus: 8
    runtime_env:
      working_dir: "."
    _temp_dir: "/tmp/ray_grpo"
    _system_config:
      object_spilling_threshold: 0.8
      max_direct_memory_size: 10737418240
      object_store_full_delay_ms: 100
      object_store_full_max_retries: 3
  collector_config:
    num_cpus: 4
  train_handler_config:
    num_cpus: 4
  replay_buffer_config:
    num_cpus: 4
    num_gpus: 0.0

logging:
  experiment_name: null
  checkpoint_dir: "checkpoints"
  checkpoint_frequency: 10

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
