# task and env
env:
  name: CartPole-v1
  task: ""
  n_samples_stats: 1000
  seed: 0
  train_num_envs: 1
  eval_num_envs: 1
  backend: gymnasium


# collector
collector:
  frames_per_batch: 200
  total_frames: 20000
  init_random_frames: 1000
  env_per_collector: 1
  device: cpu
  max_frames_per_traj: 200

# logger
logger:
  backend: wandb
  project_name: torchrl_example_discrete_iql
  exp_name: iql_${env.name}
  group_name: null
  log_interval: 5000 # record interval in frames
  eval_steps: 200
  mode: online
  eval_iter: 1000
  video: False

# replay buffer
replay_buffer:
  prb: 0
  buffer_prefetch: 64
  size: 1_000_000

# optimization
optim:
  utd_ratio: 1
  device: null
  lr: 3e-4
  weight_decay: 0.0
  batch_size: 256

# network
model:
  hidden_sizes: [256, 256]
  activation: relu


# loss
loss: 
  loss_function: l2
  gamma: 0.99
  hard_update_interval: 10

# IQL specific hyperparameter
  temperature: 100
  expectile: 0.8
