# task and env
env:
  env_name: HalfCheetah-v4
  env_task: ""
  env_library: gym
  frame_skip: 2
  num_envs: 1
  noop: 1
  reward_scaling: 1.0
  from_pixels: False
  n_samples_stats: 3

# collector
collector:
  frames_per_batch: 64
  total_frames: 1_000_000
  collector_device: cuda  # cpu
  max_frames_per_traj: -1

# logger
logger:
  backend: wandb
  exp_name: a2c_halfcheetah_gym
  log_interval: 10000

# Optim
optim:
  device: cuda
  lr: 0.0005
  weight_decay: 0.0
  lr_scheduler: False

# loss
loss:
  gamma: 0.99
  gae_lamdda: 0.95
  critic_coef: 0.5
  entropy_coef: 0.01
  loss_critic_type: l2
