# Environment
env:
  env_name: PongNoFrameskip-v4

# collector
collector:
  frames_per_batch: 1024
  total_frames: 40_000_000

# logger
logger:
  backend: wandb
  exp_name: Atari_Schulman17
  test_interval: 40_000_000
  num_test_episodes: 3

# Optim
optim:
  lr: 0.001 # 2.5e-4
  eps: 1.0e-6
  weight_decay: 0.0
  max_grad_norm: 0.5
  anneal_lr: True

# loss
loss:
  gamma: 0.99
  mini_batch_size: 1024
  gae_lambda: 0.95
  critic_coef: 1.0
  entropy_coef: 0.01
  loss_critic_type: l2
