env_name: HalfCheetah-v4
env_task: ""
env_library: gym
async_collection: 1
record_video: 0
normalize_rewards_online: 1
normalize_rewards_online_scale: 1
frame_skip: 1
frames_per_batch: 1000
optim_steps_per_batch: 1000
total_frames: 400000
prb: 0
ou_exploration: 0
multi_step: 1
init_random_frames: 5000
activation: elu
gSDE: 0
from_pixels: 0
collector_devices: [cuda:1,cuda:1,cuda:1,cuda:1]
env_per_collector: 2
num_workers: 8
value_network_update_interval: 200
record_interval: 1000
max_frames_per_traj: 1000
annealing_frames: 1000000
init_env_steps: 1000
record_frames: 1000
loss_function: smooth_l1
batch_transform: 1
buffer_prefetch: 64
norm_stats: 1
world_model_lr: 1e-3
hidden_world_model: 256
num_layers_world_model: 4
start_imagination_horizon: 1
start_imagination_horizon_epoch: 20
end_imagination_horizon: 1
end_imagination_horizon_epoch: 100
sac_lr: 3e-4
model_batch_size: 256
sac_batch_size: 256
real_data_ratio: 0.05
num_world_models_ensemble: 7
num_elites: 5
num_model_rollouts: 400
keep_model_samples_n_collect_steps: 1
num_sac_training_steps_per_optim_step: 40
train_model_every_k_optim_step: 250
model_buffer_size: 400000
model_holdout_ratio: 0.2
logger: wandb
