env_name: ALE/Pong-v5
env_task: ""
env_library: gym
async_collection: 1
record_video: 1
normalize_rewards_online: 1
normalize_rewards_online_scale: 5
frame_skip: 4
noops: 30
frames_per_batch: 1024
optim_steps_per_batch: 128
batch_size: 256
total_frames: 1000000
prb: 1
lr: 3e-4
multi_step: 1
init_random_frames: 25000
from_pixels: 1
collector_device: cpu
env_per_collector: 8
num_workers: 32
lr_scheduler: ""
value_network_update_interval: 200
record_interval: 10
max_frames_per_traj: -1
weight_decay: 0.0
annealing_frames: 1000000
init_env_steps: 10000
record_frames: 50000
loss_function: smooth_l1
batch_transform: 1
buffer_prefetch: 64
catframes: 4
