# Environment
env:
  env_name: PongNoFrameskip-v4

# Ray init kwargs - https://docs.ray.io/en/latest/ray-core/api/doc/ray.init.html
ray_init_config:
  address: None
  num_cpus: None
  num_gpus: None
  resources: None
  object_store_memory: None
  local_mode: False
  ignore_reinit_error: False
  include_dashboard: None
  dashboard_host: "127.0.0.1"
  dashboard_port: None
  job_config: None
  configure_logging: True
  logging_level: "info"
  logging_format: None
  log_to_driver: True
  namespace: None
  runtime_env: None
  storage: None

# Resources assigned to each IMPALA rollout collection worker
remote_worker_resources:
  num_cpus: 1
  num_gpus: 0.25
  memory: 2 * 1024**3

# collector
collector:
  frames_per_batch: 80
  total_frames: 200_000_000
  num_workers: 12

# logger
logger:
  backend: wandb
  exp_name: Atari_Schulman17
  test_interval: 200_000_000
  num_test_episodes: 3

# Optim
optim:
  lr: 0.0006
  eps: 1e-8
  weight_decay: 0.0
  momentum: 0.0
  alpha: 0.99
  max_grad_norm: 40.0
  anneal_lr: True

# loss
loss:
  gamma: 0.99
  batch_size: 32
  sgd_updates: 1
  critic_coef: 0.5
  entropy_coef: 0.01
  loss_critic_type: l2
