# Environment
env:
  env_name: PongNoFrameskip-v4

# collector
collector:
  frames_per_batch: 128 # 80
  total_frames: 40_000_000
  num_workers: 12

# logger
logger:
  backend: wandb
  exp_name: Atari_Espeholt18
  test_interval: 40_000_000
  num_test_episodes: 3

# Optim
optim:
  lr: 0.0006 # 0.0001
  eps: 1.0e-5
  weight_decay: 0.0
  max_grad_norm: 40.0
  anneal_lr: True

# loss
loss:
  gamma: 0.99
  mini_batch_size: 128 # 80
  critic_coef: 0.25
  entropy_coef: 0.01
  loss_critic_type: l2

