
# task and env
env:
  name: CartPole-v1
  task: ""
  library: gym
  seed: 42
  max_episode_steps: 500

# collector
collector:
  total_frames: 25000
  init_random_frames: 1000
  init_env_steps: 1000
  frames_per_batch: 500
  reset_at_each_iter: False
  device: null
  env_per_collector: 1
  num_workers: 1

# replay buffer
replay_buffer:
  prb: 0 # use prioritized experience replay
  size: 1000000
  scratch_dir: null

# optim
optim:
  utd_ratio: 1.0
  gamma: 0.99
  batch_size: 256
  lr: 3.0e-4
  weight_decay: 0.0
  target_update_polyak: 0.995
  target_entropy_weight: 0.2
  target_entropy: "auto"
  loss_function: l2
  # default is 0.98 but needs to be decreased for env
  # with small action space

# network
network:
  hidden_sizes: [256, 256]
  activation: relu
  device: null

compile:
  compile: False
  compile_mode:
  cudagraphs: False

# logging
logger:
  backend: wandb
  project_name: torchrl_example_discrete_sac
  group_name: null
  exp_name: ${env.name}_DiscreteSAC
  mode: online
  eval_iter: 5000
  video: False
