# Environment
env:
  env_name: PongNoFrameskip-v4
  num_envs: 8

# collector
collector:
  frames_per_batch: 2560
  total_frames: 40_000_000

# logger
logger:
  backend: wandb
  exp_name: Atari_Schulman17
  test_interval: 40_000_000
  num_test_episodes: 3

# Optim
optim:
  lr: 0.0006
  eps: 1.0e-6
  weight_decay: 0.0
  max_grad_norm: 0.5
  anneal_lr: True

# loss
loss:
  gamma: 0.99
  mini_batch_size: 2560
  ppo_epochs: 1
  gae_lambda: 0.95
  clip_epsilon: 0.1
  anneal_clip_epsilon: True
  critic_coef: 0.5
  entropy_coef: 0.01
  loss_critic_type: l2
