# environment and task
env:
  name: HalfCheetah-v4
  task: ""
  library: gymnasium
  max_episode_steps: 1000
  seed: 42

# collector
collector:
  total_frames: -1
  init_random_frames: 25000
  frames_per_batch: 8000
  init_env_steps: 1000
  device: cuda:1
  env_per_collector: 16
  reset_at_each_iter: False
  update_freq: 10_000

# replay buffer
replay_buffer:
  size: 100_000 # Small buffer size to keep only recent elements
  prb: 0 # use prioritized experience replay
  scratch_dir:

# optim
optim:
  utd_ratio: 1.0
  gamma: 0.99
  loss_function: l2
  lr: 3.0e-4
  weight_decay: 0.0
  batch_size: 256
  target_update_polyak: 0.995
  alpha_init: 1.0
  adam_eps: 1.0e-8

# network
network:
  hidden_sizes: [256, 256]
  activation: relu
  default_policy_scale: 1.0
  scale_lb: 0.1
  device:

# logging
logger:
  backend: wandb
  project_name: torchrl_example_sac
  group_name: null
  exp_name: ${env.name}_SAC
  mode: online
  log_freq: 25000  # logging freq in updates
  video: False

compile:
  compile: False
  compile_mode:
  cudagraphs: False
