channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - pip:
    - hypothesis
    - future
    - cloudpickle
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-instafail
    - pytest-rerunfailures
    - pytest-error-for-skips
    - expecttest
    - pybind11[global]
    - pyyaml
    - scipy
    - hydra-core
    - transformers
    - openenv-core>=0.3.0,<0.4.0
