# Environment
env:
  env_name: PongNoFrameskip-v4
  num_envs: 4

# collector
collector:
  frames_per_batch: 320
  total_frames: 200_000_000

# logger
logger:
  backend: wandb
  exp_name: Atari_Schulman17
  test_interval: 200_000_000
  num_test_episodes: 3

# Optim
optim:
  lr: 0.0006
  eps: 0.01
  weight_decay: 0.0
  momentum: 0.0
  alpha: 0.99
  max_grad_norm: 1.0
  anneal_lr: True

# loss
loss:
  gamma: 0.99
  batch_size: 8
  sgd_updates: 1
  critic_coef: 0.25
  entropy_coef: 0.01
  loss_critic_type: l2
