# environment and task
env:
  name: HalfCheetah-v4
  task: ""
  library: gym
  max_episode_steps: 1000
  seed: 42

# collector
collector:
  total_frames: 1_000_000
  init_random_frames: 25000
  frames_per_batch: 1000
  init_env_steps: 1000
  device: cpu
  env_per_collector: 1
  reset_at_each_iter: False

# replay buffer
replay_buffer:
  size: 1000000
  prb: 0 # use prioritized experience replay
  scratch_dir: null

# optim
optim:
  utd_ratio: 1.0
  policy_update_delay: 3
  gamma: 0.99
  loss_function: l2
  lr: 1.0e-3
  weight_decay: 0.0
  batch_size: 256
  alpha_init: 1.0
  adam_eps: 1.0e-8
  beta1: 0.5
  beta2: 0.999

# network
network:
  batch_norm_momentum: 0.01
  warmup_steps: 100000 
  critic_hidden_sizes: [2048, 2048]
  actor_hidden_sizes: [256, 256]
  critic_activation: relu
  actor_activation: relu
  default_policy_scale: 1.0
  scale_lb: 0.1
  device: "cuda:0"

# logging
logger:
  backend: wandb
  project_name: torchrl_example_crossQ
  group_name: null
  exp_name: ${env.name}_CrossQ
  mode: online
  eval_iter: 25000
