- _target_: torchrl.envs.transforms.ToTensorImage
  in_keys: ["pixels"]
- _target_: torchrl.envs.transforms.Resize
  w: 64
  h: 64
  in_keys: ["pixels"]
- _target_: torchrl.envs.transforms.GrayScale
  in_keys: ["pixels"]
- _target_: torchrl.envs.transforms.ObservationNorm
  in_keys: ["pixels"]
  loc: 0.0
  scale: 1.0
- _target_: torchrl.envs.transforms.CatFrames
  in_keys: ["pixels"]
  N: 4
  cat_dim: -3
- _target_: torchrl.envs.transforms.RewardScaling
  loc: 0.0
  scale: 1.0