# task and env
env:
  name: HalfCheetah-v4
  task: ""
  library: gymnasium
  seed: 42
  max_episode_steps: 1000

# replay buffer
replay_buffer:
  dataset: halfcheetah-medium-v2  # set to null to collect demos from env
  demo_episodes: 50  # only used when dataset is null
  batch_size: 256

# optim
optim:
  gradient_steps: 100000
  lr: 1.0e-4
  weight_decay: 0.0
  adam_eps: 1.0e-8
  clip_grad: 1.0

# diffusion model
network:
  hidden_sizes: [256, 256]
  activation: silu
  num_steps: 100
  beta_start: 1.0e-4
  beta_end: 0.02
  device: cpu

# logging
logger:
  backend: wandb
  project_name: diffusion_bc
  group_name: null
  exp_name: DiffusionBC_${env.name}
  mode: online
  eval_iter: 5000
  eval_steps: 1000
  eval_envs: 1
  video: False

compile:
  compile: False
  compile_mode:
  cudagraphs: False
