env_name: HalfCheetah-v4
env_task: ""
env_library: gym
async_collection: 0
record_video: 1
normalize_rewards_online: 1
normalize_rewards_online_scale: 5
frame_skip: 1
frames_per_batch: 1000
optim_steps_per_batch: 20
batch_size: 256  # each training batch will have 256 frames
sub_traj_len: 64  # we want 4 trajectories of length 64 = 256 frames
total_frames: 1000000
lr: 1e-3
from_pixels: 0
#collector_devices: [cuda:1]
collector_devices: [cpu]
env_per_collector: 2
num_workers: 2
lr_scheduler: ""
record_interval: 100
max_frames_per_traj: -1
weight_decay: 0.0
init_env_steps: 10000
record_frames: 50000
loss_function: smooth_l1
batch_transform: 1
entropy_coef: 0.01
