# task and env
env:
  env_name: HalfCheetah-v4
  env_task: ""
  env_library: gym
  frame_skip: 1
  num_envs: 1
  noop: 1
  reward_scaling: 1.0
  from_pixels: False
  n_samples_stats: 3

# collector
collector:
  async_collection: 0
  frames_per_batch: 2048
  total_frames: 10_000_000
  collector_devices: cuda  # [cpu,cpu,cpu,cpu]
  num_collectors: 1
  max_frames_per_traj: -1

# eval
recorder:
  video: False
  interval: 10000  # record interval in frames
  frames: 10000

# logger
logger:
  backend: wandb
  exp_name: ppo_pong_gym

# Optim
optim:
  device: cuda
  lr: 2.0e-4
  weight_decay: 0.0

# loss
loss:
  gamma: 0.99
  mini_batch_size: 64
  ppo_epochs: 10
  gae_lamdda: 0.95
  clip_epsilon: 0.2
  critic_coef: 0.5
  entropy_coef: 0.0
  loss_critic_type: l2
