# task and env
env:
  env_name: PongNoFrameskip-v4
  env_task: ""
  env_library: gym
  frame_skip: 4
  num_envs: 8
  noop: 1
  reward_scaling: 1.0
  from_pixels: True
  n_samples_stats: 3

# collector
collector:
  frames_per_batch: 4096
  total_frames: 40_000_000
  collector_device: cuda  # cpu
  max_frames_per_traj: -1

# logger
logger:
  backend: wandb
  exp_name: ppo_pong_gym
  log_interval: 10000

# Optim
optim:
  device: cuda
  lr: 2.5e-4
  weight_decay: 0.0
  lr_scheduler: True

# loss
loss:
  gamma: 0.99
  mini_batch_size: 1024
  ppo_epochs: 3
  gae_lamdda: 0.95
  clip_epsilon: 0.1
  critic_coef: 0.5
  entropy_coef: 0.01
  loss_critic_type: l2
