# task and env
env:
  name: HalfCheetah-v4  # Use v4 to get rid of mujoco-py dependency
  task: ""
  library: gymnasium
  seed: 42
  max_episode_steps: 1000

# collector
collector:
  total_frames: 1000000
  init_random_frames: 25_000
  init_env_steps: 1000
  frames_per_batch: 1000
  reset_at_each_iter: False
  device: cpu
  env_per_collector: 1
  num_workers: 1

# replay buffer
replay_buffer:
  prb: 0 # use prioritized experience replay
  size: 1000000
  scratch_dir: null

# optim
optim:
  utd_ratio: 1.0
  gamma: 0.99
  loss_function: l2
  lr: 3.0e-4
  weight_decay: 0.0
  adam_eps: 1e-4
  batch_size: 256
  target_update_polyak: 0.995
  policy_update_delay: 2
  policy_noise: 0.2
  noise_clip: 0.5

# network
network:
  hidden_sizes: [256, 256]
  activation: relu
  device: null

# logging
logger:
  backend: wandb
  project_name: torchrl_example_td3
  group_name: null
  exp_name: ${env.name}_TD3
  mode: online
  eval_iter: 25000
  video: False
