seed: 0

env:
  continuous_actions: True # False for discrete sac
  max_steps: 100
  scenario_name: "balance"
  scenario:
    n_agents: 3
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

model:
  shared_parameters: True
  centralised_critic: True

collector:
  frames_per_batch: 60_000 # Frames sampled each sampling iteration
  n_iters: 500 # Number of sampling/training iterations
  total_frames: ???

buffer:
  memory_size: ???

loss:
  gamma: 0.9
  tau: 0.005 # For target net

train:
  num_epochs: 45  # optimization steps per batch of data collected
  minibatch_size: 4096 # size of minibatches used in each epoch
  lr: 5e-5
  max_grad_norm: 2.0
  device: ???

eval:
  evaluation_interval: 20
  evaluation_episodes: 200

logger:
  backend: wandb # Delete to remove logging
