channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - protobuf
  - pip:
    - hypothesis
    - future
    - cloudpickle
    - gymnasium
    - pygame
    - gymnasium[accept-rom-license]
    - gymnasium[atari]
    - moviepy
    - tqdm
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-instafail
    - pytest-rerunfailures
    - expecttest
    - pyyaml
    - scipy
    - hydra-core
    - tensorboard
    - wandb
    - dm_control
    - mlflow
    - av
    - coverage
