# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
"""TRL Interoperability Adapters for TorchRL.

This module provides thin adapters that allow seamless interoperability between
TorchRL and Hugging Face ``trl``:

* :class:`TorchRLBufferDataset` — wraps a :class:`~torchrl.data.ReplayBuffer` as a
  ``torch.utils.data.IterableDataset`` so that ``trl`` trainers (e.g.
  ``GRPOTrainer``, ``PPOTrainer``) can directly consume token / trajectory data
  generated by TorchRL collectors.

* :class:`HFRewardModelWrapper` — wraps a Hugging Face reward model (e.g., one
  trained via ``trl.RewardTrainer``) as a
  :class:`~tensordict.nn.TensorDictModuleBase` so it can be plugged into any
  TorchRL training loop, including GRPO recipes, without any boilerplate.

Both classes are **optional-dependency-guarded**: importing this module never
requires ``transformers`` or ``trl`` to be installed; the dependency is only
checked at instantiation time.
"""

from __future__ import annotations

import contextlib
import importlib.util
from typing import Any
from collections.abc import Iterator

import torch
from tensordict import TensorDictBase
from tensordict.nn import TensorDictModuleBase
from tensordict.utils import NestedKey
from torch import nn

from torchrl._utils import logger as torchrl_logger
from torchrl.data.replay_buffers import ReplayBuffer

_has_transformers = importlib.util.find_spec("transformers") is not None

__all__ = [
    "TorchRLBufferDataset",
    "HFRewardModelWrapper",
]


# ---------------------------------------------------------------------------
# TorchRLBufferDataset — TorchRL -> TRL
# ---------------------------------------------------------------------------


class TorchRLBufferDataset(torch.utils.data.IterableDataset):
    """An :class:`torch.utils.data.IterableDataset` backed by a TorchRL :class:`~torchrl.data.ReplayBuffer`.

    This adapter allows ``trl`` trainers (e.g. :class:`trl.GRPOTrainer`,
    :class:`trl.PPOTrainer`) to directly consume token / trajectory data
    produced by TorchRL collectors.

    Each call to ``__iter__`` samples one batch of size ``batch_size`` from the
    replay buffer and yields individual samples as flat ``dict[str, Any]``
    objects.  This matches the format expected by HuggingFace
    ``DataCollatorWithPadding`` and the standard ``Trainer`` / trl trainer
    data pipeline.

    .. note::
        This class implements :class:`torch.utils.data.IterableDataset` (no
        ``__len__``), which is the safest choice for online / infinite replay
        buffers.  If you need a finite dataset with a known length, iterate
        for a fixed number of steps yourself and collect the results.

    Args:
        replay_buffer (:class:`~torchrl.data.ReplayBuffer`): the TorchRL
            replay buffer to wrap.
        batch_size (int): number of samples to draw from the buffer per
            internal sampling call.  Each yielded item is one *individual*
            sample (no leading batch dimension).

    Keyword Args:
        keys (list of :class:`~tensordict.NestedKey`, optional): if provided,
            only these keys are included in the yielded dicts.  Nested keys
            are serialised as ``"key0.key1"`` strings so they remain
            compatible with HuggingFace collators.  Defaults to ``None``
            (all top-level keys).
        device (torch.device or str, optional): if provided, all tensors are
            moved to this device before yielding.  Defaults to ``None``
            (tensors stay on their current device).

    Examples:
        >>> import torch
        >>> from tensordict import TensorDict
        >>> from torchrl.data import ReplayBuffer, ListStorage
        >>> from torchrl.modules.llm.trl_interop import TorchRLBufferDataset
        >>>
        >>> rb = ReplayBuffer(storage=ListStorage(100), batch_size=4)
        >>> for _ in range(10):
        ...     rb.add(TensorDict({"input_ids": torch.randint(0, 100, (8,)),
        ...                        "attention_mask": torch.ones(8, dtype=torch.long)},
        ...                       batch_size=[]))
        >>>
        >>> dataset = TorchRLBufferDataset(rb, batch_size=4)
        >>> for sample in dataset:
        ...     print({k: v.shape for k, v in sample.items() if hasattr(v, "shape")})
        ...     break

    .. seealso::
        :class:`HFRewardModelWrapper` for the reverse direction (TRL -> TorchRL).
    """

    def __init__(
        self,
        replay_buffer: ReplayBuffer,
        batch_size: int,
        *,
        keys: list[NestedKey] | None = None,
        device: torch.device | str | None = None,
    ) -> None:
        if not isinstance(replay_buffer, ReplayBuffer):
            raise TypeError(
                f"replay_buffer must be a torchrl ReplayBuffer instance, "
                f"got {type(replay_buffer).__name__}."
            )
        if not isinstance(batch_size, int) or batch_size <= 0:
            raise ValueError(
                f"batch_size must be a positive integer, got {batch_size!r}."
            )
        self._replay_buffer = replay_buffer
        self._batch_size = batch_size
        self._keys = keys
        self._device = torch.device(device) if device is not None else None

    # ------------------------------------------------------------------
    # IterableDataset protocol
    # ------------------------------------------------------------------

    def __iter__(self) -> Iterator[dict[str, Any]]:
        """Sample one batch from the buffer and yield individual samples."""
        batch: TensorDictBase = self._replay_buffer.sample(self._batch_size)

        if self._keys is not None:
            key_list = self._keys
        else:
            key_list = list(batch.keys())

        for i in range(batch.batch_size[0]):
            sample_td = batch[i]
            out: dict[str, Any] = {}
            for key in key_list:
                try:
                    value = sample_td.get(key)
                except KeyError:
                    torchrl_logger.warning(
                        f"TorchRLBufferDataset: key {key!r} not found in sampled "
                        "TensorDict -- skipping."
                    )
                    continue
                if value is None:
                    continue
                if self._device is not None and hasattr(value, "to"):
                    value = value.to(self._device)
                if isinstance(key, str):
                    str_key: str = key
                else:
                    str_key = ".".join(str(k) for k in key)
                out[str_key] = value
            yield out

    def __repr__(self) -> str:
        keys_repr = self._keys if self._keys is not None else "<all>"
        return (
            f"{self.__class__.__name__}("
            f"replay_buffer={self._replay_buffer!r}, "
            f"batch_size={self._batch_size}, "
            f"keys={keys_repr}, "
            f"device={self._device})"
        )


# ---------------------------------------------------------------------------
# HFRewardModelWrapper — TRL -> TorchRL
# ---------------------------------------------------------------------------


class _HFRewardModule(nn.Module):
    """Inner nn.Module that calls the HF reward model and returns a scalar reward tensor.

    This is kept separate from :class:`HFRewardModelWrapper` so that
    :class:`~tensordict.nn.TensorDictModuleBase` controls all TensorDict
    bookkeeping while this class focuses purely on the HF model call.
    """

    def __init__(
        self,
        model: nn.Module,
        *,
        inference_mode: bool,
    ) -> None:
        super().__init__()
        self.model = model
        self._inference_mode = inference_mode

    def forward(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor | None,
    ) -> torch.Tensor:
        """Call the HF reward model and return a 1-D reward tensor of shape ``[B]``."""
        if self._inference_mode:
            ctx = torch.inference_mode()
        else:
            ctx = contextlib.nullcontext()

        with ctx:
            out = self.model(
                input_ids=input_ids,
                attention_mask=attention_mask,
            )

        # HF reward models typically return a ModelOutput with a ``logits``
        # attribute of shape [B, 1] or [B].  Handle both shapes.
        if hasattr(out, "logits"):
            rewards: torch.Tensor = out.logits
        elif hasattr(out, "rewards"):
            rewards = out.rewards
        elif isinstance(out, torch.Tensor):
            rewards = out
        else:
            raise RuntimeError(
                "HFRewardModelWrapper: could not extract reward from model output. "
                f"Got type {type(out).__name__}. Expected an output with a 'logits' "
                "or 'rewards' attribute, or a bare torch.Tensor."
            )

        if rewards.ndim > 1:
            rewards = rewards.squeeze(-1)
        return rewards.float()


class HFRewardModelWrapper(TensorDictModuleBase):
    """A :class:`~tensordict.nn.TensorDictModuleBase` that wraps a Hugging Face reward model.

    This adapter allows any HuggingFace sequence-classification / reward model
    (e.g., one trained via ``trl.RewardTrainer`` or
    ``transformers.AutoModelForSequenceClassification``) to be used as a reward
    signal inside a TorchRL training loop, including GRPO / PPO recipes.

    On :meth:`forward`, the wrapper:

    1. Reads ``token_key`` (input token ids) and ``attention_mask_key`` from
       the incoming :class:`~tensordict.TensorDictBase`.
    2. Calls the wrapped HF model with ``input_ids`` and ``attention_mask``.
    3. Extracts the scalar reward (``logits`` or ``rewards`` attribute, squeezed
       to shape ``[B]``).
    4. Writes the reward to ``reward_key`` in the output TensorDict.

    Args:
        model (nn.Module): a Hugging Face reward model.  Typically an instance
            of ``AutoModelForSequenceClassification`` or any model whose
            ``forward`` accepts ``input_ids`` + ``attention_mask`` and returns
            an output with a ``logits`` attribute of shape ``[B, 1]`` or ``[B]``.

    Keyword Args:
        token_key (:class:`~tensordict.NestedKey`, optional): key from which
            ``input_ids`` are read.  Defaults to ``("tokens", "full")``,
            matching the :class:`~torchrl.modules.llm.policies.Tokens` layout
            used by TorchRL LLM wrappers.
        attention_mask_key (:class:`~tensordict.NestedKey` or ``None``, optional):
            key from which the attention mask is read.  Pass ``None`` to omit
            the attention mask (model must support this).  Defaults to
            ``("masks", "all_attention_mask")``.
        reward_key (:class:`~tensordict.NestedKey`, optional): key under which
            the scalar reward tensor (shape ``[B]``) is written.  Defaults to
            ``"reward"``.
        inference_mode (bool, optional): if ``True``, the model forward pass is
            wrapped in :func:`torch.inference_mode`, which disables gradient
            computation and is more memory-efficient.  Set to ``False`` (the
            default) when you need gradients (e.g. for a differentiable critic
            loss in PPO / GRPO).  Defaults to ``False``.

    Examples:
        >>> import torch
        >>> from tensordict import TensorDict
        >>> from torchrl.modules.llm.trl_interop import HFRewardModelWrapper
        >>>
        >>> class DummyRewardModel(torch.nn.Module):
        ...     def forward(self, input_ids, attention_mask=None):
        ...         class Out:
        ...             logits = torch.randn(input_ids.shape[0], 1)
        ...         return Out()
        >>>
        >>> wrapper = HFRewardModelWrapper(DummyRewardModel())
        >>> td = TensorDict(
        ...     {
        ...         "tokens": {"full": torch.randint(0, 1000, (2, 16))},
        ...         "masks": {"all_attention_mask": torch.ones(2, 16, dtype=torch.long)},
        ...     },
        ...     batch_size=[2],
        ... )
        >>> result = wrapper(td)
        >>> print(result["reward"].shape)
        torch.Size([2])

    .. seealso::
        :class:`TorchRLBufferDataset` for the reverse direction (TorchRL -> TRL).
    """

    def __init__(
        self,
        model: nn.Module,
        *,
        token_key: NestedKey = ("tokens", "full"),
        attention_mask_key: NestedKey | None = ("masks", "all_attention_mask"),
        reward_key: NestedKey = "reward",
        inference_mode: bool = False,
    ) -> None:
        in_keys: list[NestedKey] = [token_key]
        if attention_mask_key is not None:
            in_keys.append(attention_mask_key)

        out_keys: list[NestedKey] = [reward_key]

        super().__init__()

        self.in_keys = in_keys
        self.out_keys = out_keys

        self._token_key = token_key
        self._attention_mask_key = attention_mask_key
        self._reward_key = reward_key

        self._reward_module = _HFRewardModule(model, inference_mode=inference_mode)

    # ------------------------------------------------------------------
    # Public accessors
    # ------------------------------------------------------------------

    @property
    def model(self) -> nn.Module:
        """The underlying HF reward model."""
        return self._reward_module.model

    # ------------------------------------------------------------------
    # TensorDictModuleBase forward
    # ------------------------------------------------------------------

    def forward(self, tensordict: TensorDictBase) -> TensorDictBase:
        """Read tokens from ``tensordict``, call the reward model, write reward back.

        Args:
            tensordict (:class:`~tensordict.TensorDictBase`): input data.
                Must contain the keys specified by ``token_key`` and, if not
                ``None``, ``attention_mask_key``.

        Returns:
            The same (modified in-place) :class:`~tensordict.TensorDictBase`
            with the scalar reward tensor written to ``reward_key``.
        """
        input_ids: torch.Tensor = tensordict.get(self._token_key)
        if input_ids is None:
            raise KeyError(
                f"HFRewardModelWrapper: token_key {self._token_key!r} not found "
                "in the input TensorDict."
            )

        attention_mask: torch.Tensor | None = None
        if self._attention_mask_key is not None:
            attention_mask = tensordict.get(self._attention_mask_key, default=None)

        reward = self._reward_module(input_ids, attention_mask)

        tensordict.set(self._reward_key, reward)
        return tensordict
