_target_: torchrl.collectors.SyncDataCollector
_partial_: True

# Parameters
total_frames: 5000000
create_env_kwargs: null
max_frames_per_traj: int = -1,
frames_per_batch: 200
init_random_frames: -1
reset_at_each_iter: False
postproc: null
split_trajs: null
device: "cpu"
passing_device: "cpu"
seed: 42
pin_memory: False
return_in_place: False
exploration_mode: "random"
init_with_lag: False
return_same_td: False
reset_when_done: True

# Partial parameters
create_env_fn: MISSING
policy: MISSING
