name: Olddeps Tests on Linux

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

jobs:
  unittests:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      repository: pytorch/rl
      runner: "linux.g5.4xlarge.nvidia.gpu"
      # gpu-arch-type: cuda
      # gpu-arch-version: "11.7"
      docker-image: "nvidia/cudagl:11.4.0-base"
      timeout: 120
      script: |
        set -euo pipefail
        export PYTHON_VERSION="3.9"
        export CU_VERSION="cu116"
        export TAR_OPTIONS="--no-same-owner"
        export UPLOAD_CHANNEL="nightly"
        export TF_CPP_MIN_LOG_LEVEL=0


        bash .circleci/unittest/linux_olddeps/scripts_gym_0_13/setup_env.sh
        bash .circleci/unittest/linux_olddeps/scripts_gym_0_13/batch_scripts.sh
        bash .circleci/unittest/linux_olddeps/scripts_gym_0_13/post_process.sh
