name: Minari Tests on Linux

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On master, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && format('ci-master-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  unittests:
    strategy:
      matrix:
        python_version: ["3.9"]
        cuda_arch_version: ["12.1"]
    if: ${{ github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'Data') }}
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      repository: pytorch/rl
      runner: "linux.g5.4xlarge.nvidia.gpu"
      docker-image: "nvidia/cudagl:11.4.0-base"
      timeout: 120
      script: |
        set -euo pipefail
        export PYTHON_VERSION="3.9"
        export CU_VERSION="cu117"
        export TAR_OPTIONS="--no-same-owner"
        export UPLOAD_CHANNEL="nightly"
        export TF_CPP_MIN_LOG_LEVEL=0

        bash .github/unittest/linux_libs/scripts_minari/setup_env.sh
        bash .github/unittest/linux_libs/scripts_minari/install.sh
        bash .github/unittest/linux_libs/scripts_minari/run_test.sh
        bash .github/unittest/linux_libs/scripts_minari/post_process.sh
